---
- name: Install xorg
  pacman:
    state: present
    name:
      - xorg-server
      - xorg-init
      - xorg-font-util
      - xorg-fonts-encondings
      - xterm
      - rxvt-unicode
    tags:
      - xorg

- name: Install fonts
  pacman:
    state: present
    name:
      - adobe-source-code-pro-fonts
      - noto-fonts-emoji
      - terminus-font
      - ttf-fira-mono
      - ttf-inconsolata
      - ttf-roboto
    tags:
      - fonts

- name: Install window manager
  pacman:
    state: present
    name:
      - i3-gaps
      - i3blocks
    tags:
      - wm

- name: Install background manager
  pacman:
    state: present
    name:
      - nitrogen
    tags:
      - nitrogen

- name: Install wm utils
  pacman:
    state: present
    name:
      - rofi
      - ranger
      - w3m
