---
- name: Copy pacman configuration
  templates:
    src: pacman.conf
    dest: "/etc/pacman.conf"
  when: inventory_hostname in groups['pc']

- name: Full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install zsh
  pacman:
    name:
      - zsh
    state: present
  tags:
    - shell

- name: Install universal base packages
  pacman:
    state: present
    name:
      - python
      - base-devel
      - git
    tags:
      - packages

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes
  tags:
    - sudo

- name: Ensure UTF8 US locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set locale
  copy:
    dest: "/etc/locale.conf"
    content: "LANG=en_US.UTF-8"

- name: Set timezone
  timezone:
    name: America/Montreal
